# Generated by Django 5.2.12 on 2026-04-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_platformnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='UG', max_length=2),
        ),
    ]
