# Generated by Django 5.2.12 on 2026-04-10 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_college_registration_number_college_status_and_more'),
        ('management', '0003_department_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='management.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.specialization'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.specialization'),
        ),
    ]
