# Generated by Django 5.2.12 on 2026-04-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_specialization_studentprofile_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/photos/'),
        ),
    ]
