# Generated by Django 5.2.12 on 2026-04-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_attendance_marked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_passout_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='plus_two_marklist',
            field=models.FileField(blank=True, null=True, upload_to='students/marks/plustwo/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ug_marklist',
            field=models.FileField(blank=True, null=True, upload_to='students/marks/ug/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='university_reg_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
