# Generated by Django 5.2.12 on 2026-04-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_studentprofile_address_studentprofile_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
    ]
