# Generated by Django 5.2.12 on 2026-06-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_collegeimage_category'),
        ('management', '0009_studentprofile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('number_of_periods', models.IntegerField(default=6)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_classes', to='management.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
