# Generated by Django 5.2.12 on 2026-06-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_academicclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.academicclass'),
        ),
    ]
