# Generated by Django 5.2.12 on 2026-06-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_studentprofile_academic_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.academicclass'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'period')},
        ),
    ]
