# Generated by Django 5.2.12 on 2026-06-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_attendance_academic_class_attendance_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclass',
            name='max_internal_marks',
            field=models.IntegerField(default=100),
        ),
    ]
