# Generated by Django 5.2.12 on 2026-06-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_collegeimage_category'),
        ('management', '0014_internalmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicclass',
            name='max_internal_marks',
        ),
        migrations.CreateModel(
            name='InternalMarkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('max_marks', models.IntegerField(default=10)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_mark_categories', to='management.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='internalmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='internalmark',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to='management.internalmarkcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='internalmark',
            unique_together={('student', 'academic_class', 'category')},
        ),
    ]
