# Generated by Django 5.2.12 on 2026-06-24 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_collegeimage_category'),
        ('management', '0015_remove_academicclass_max_internal_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='academic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='management.academicclass'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='timetables/'),
        ),
        migrations.CreateModel(
            name='TimeTablePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
                ('period_number', models.IntegerField()),
                ('subject_name', models.CharField(blank=True, max_length=255, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_periods', to='management.teacherprofile')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='management.timetable')),
            ],
            options={
                'ordering': ['day_of_week', 'period_number'],
                'unique_together': {('timetable', 'day_of_week', 'period_number')},
            },
        ),
    ]
