# Generated by Django 4.2.30 on 2026-07-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_collegeenquiry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='internalmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='internalmark',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to='management.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='internalmark',
            unique_together={('student', 'academic_class', 'subject', 'category')},
        ),
    ]
