# Generated by Django 5.2.12 on 2026-04-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_college_registration_number_college_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, help_text='Briefly describe your institution.'),
        ),
        migrations.AddField(
            model_name='college',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
