# Generated by Django 5.2.12 on 2026-04-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_collegeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='university_affiliation',
            field=models.CharField(blank=True, help_text='Comma-separated list of affiliated universities.', max_length=500),
        ),
    ]
