# Generated by Django 5.2.12 on 2026-04-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_collegeachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection, shown to the institution.', null=True),
        ),
    ]
