# Generated by Django 5.2.12 on 2026-04-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_college_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='slug_updated',
            field=models.BooleanField(default=False),
        ),
    ]
