# Generated by Django 5.2.12 on 2026-04-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_college_slug_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeimage',
            name='category',
            field=models.CharField(choices=[('CAMPUS', 'Campus Infrastructure'), ('AMENITY', 'Amenities & Life'), ('FACILITY', 'Academic Facilities'), ('EVENT', 'Events & Activity'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
